### ISSUE TITLE
WarpEx: plugin.ini cannot be modified

### ISSUE THREAD

**Issue by teejo75** [palm3r/Hey0Plugins#1]
Every time the plugin starts, it rewrites the plugin.ini, so any changes made to the default namespace are lost.  ie, I prefer default-namespace = Global, but every time I change the setting and reload the plugin, the file gets rewritten.

**Comment by palm3r** [comment]
fixed in v1.21
thanks

**Comment by teejo75** [comment]
Damn, that was quick. Thanks!
